version: '3'

services:
    registration-service:
        image: 'register-svc'
        build:
            context: ./registration-service/
        container_name: 'register'
        depends_on:
            - db
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kennel-tracker
            - SPRING_DATASOURCE_USERNAME=SRM
            - SPRING_DATASOURCE_PASSWORD=COS
            - SPRING_DATA_JPA_HIBERNATE_DDL_AUTO=update
    
    db:
        image: 'kennel-tracker-db'
        build:
            context: ./postgres-db/
        volumes:
            - ./postgres/bigdata:/var/lib/postgresql/data
        expose:
            - "5432"
        environment:
            - POSTGRES_USER=SRM
            - POSTGRES_PASSWORD=COS
